Add linters and documentation to the project
LDouglasOT/Microverse_linters pull request #3
Opened 2022-08-17 07:58 UTC by LDouglasOT

### What does this PR do?
  - Adds the linting configurations to the project
  - Add the none required files to the .gitignore file
### Description of Task to be completed?
  - Added the readme file to the project to outline the project documentations
  - Added the linting configurations for the project

2022-08-17 10:03 UTC, zieeco requested changes
Hi @LDouglasOT,


Great job so far with setting up the Hello Microverse project! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Descriptive PR. ✔️
- Nice Project Setup ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 10:03 UTC, zieeco commented on .gitignore
> +package-lock.json
- Please, kindly remove the `package-lock.json` from the gitignore as it's meant to be visible in your Project repo
- Add the missing `test.md` file to meet the project requirement

2022-08-17 10:03 UTC, zieeco commented on style.css
> +}
- Ensure you've added the `index.html` file with an `h1` with its text content to meet the project requirement.

2022-08-17 10:03 UTC, zieeco commented on readme.md
> +# fix linters errors
*README FILE*
- Kindly rename the `readme.md` to `README.md`
- Kindly add a descriptive `README.md` file. you can use this [template](https://github.com/microverseinc/readme-template) but customize it to suit your project needs.

2022-08-17 10:03 UTC, zieeco commented on readme.md
> +# fix linters errors
*PR Title*

- Kindly rename the PR title to `Hello Microverse Project` as this is more descriptive.

- [OPTIONAL] - Do ensure your branch name is descriptive and in line with the changes you've made. e.g: feature, Greetings, Hello Microverse. Please, kindly bear in mind to improve this for your future projects.

2022-08-17 17:04 UTC, Kamba56 requested changes
Hi @LDouglasOT , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Meaningful commit messages
- [ ] Descriptive pull request title
- [ ] Meaningful pull request summary

 ## Required Changes ♻️
- [ ] Kindly make sure that all linter checks are passing. You can run `npx stylelint "**/*.{css,scss} --fix` to fix stylelint errors locally and commit changes and run `npx hint .` to view webhint errors and fix the change locally then commit changes.
_Check the comments under the review for more suggestions._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [Optional] I noticed you opened multiple pull requests. You should open only one pull request for every project and ask for re-review using the same PR link. Kindly take note of this please for your next projects.
- [Optional] It's better to follow commit message standards by making them capitalized and in the imperative form (Example: 'Modify readme file' instead of 'modified readme'). This way, your commit history will be more readable and more professional ✨

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 17:04 UTC, Kamba56 commented on readme.md
> +
- [ ] As requested by the previous reviewer, kindly rename your `readme.md` file to `README.md`. You can do that by renaming it locally and committing the change.

2022-08-17 17:04 UTC, Kamba56 commented on readme.md
> +
- [Optional] Consider adding steps to set up your project locally under these sections provided, this will make your work look more professional. Please feel free to remove any section that does not apply to your work.

2022-08-17 17:04 UTC, Kamba56 commented on index.html
> +<link rel="stylesheet" href="./style.css">
- [Optional] Kindly consider moving the `<link>` tag into the `<head>` element as this is HTML best practice.

2022-08-18 07:14 UTC, cynthiainga requested changes
Hi @LDouglasOT, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

 ## Highlights

- [x] Descriptive PR ✔️ 
- [ ] Meaningful commit messages ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly fix your linters errors, the linter result should be green. Linter should report NO errors 🙃 🙃 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 08:02 UTC, LDouglasOT commented
Hey @cynthiainga, please review these linter changes made. They are now passing successfully

2022-08-18 08:07 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @LDouglasOT , 




Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 09:55 UTC, merged